FROM golang:1.26-bookworm AS develop

RUN apt update && \
    apt install curl wget git iproute2 -y

WORKDIR /app

COPY ./backend/src/go.mod ./backend/src/go.sum ./
COPY ./shared /shared

RUN go mod download

RUN go install github.com/air-verse/air@latest

FROM golang:1.26 AS builder

WORKDIR /go/src/app

COPY ./src .
COPY --from=shared . /shared

RUN go mod download

RUN CGO_ENABLED=0 go build -o /go/bin/app

FROM gcr.io/distroless/static-debian12
COPY --from=builder /go/bin/app /app
CMD ["/app"]
